### ISSUE TITLE
Scheduling for win32

### ISSUE THREAD

**Issue by chd0311** [eAndrius/BitfinexLendingBot#11]
need 2 batch files in lendingbot  folder
use cmd

1)  test.bat

@rem 반복횟수. 첫번째 파라미터로 받음.
set REPEAT=%1

@rem 실행할 명령(my.app.test는 테스트케이스가 포함된 패키지명, my.app.test.InsertTest는 테스

트케이스 클래스)
set TEST=c:/godata/BitfinexLendingBot/test1.bat

@rem FOR /L %variable IN (start,step,end) DO command [command-parameters]
FOR /L %%A IN (1,1,%REPEAT%) DO %TEST%

2)  test1.bat

c:/godata/BitfinexLendingBot/BitfinexLendingBot.exe --updatelends
timeout /t 600 /nobreak

3) excute cmd
    cd %lendingbot directory%
    c:/godata/BitfinexLendingBot> test.bat 100000

* c:/godata/BitfinexLendingBot/  == my lendingbot folder, edit for you
* Support me BTC :  1MKb4UW2DdT6pwrLth85s1AJdgeB9pQsng
	              LTC :   Lfco5x2rKvv9Dj7oTHJ1zppE4753jYyrwc

**Comment by eAndrius** [comment]
Not a bug.
