### ISSUE TITLE
API error

### ISSUE THREAD

**Issue by Mikadily** [eAndrius/BitfinexLendingBot#4]
Bot stopped working with this error:

2015/04/05 19:10:59 WARNING: Failed to get wallet funds, skipping: API: Must specify a 'request' field in the payload that matches the URL path.

**Comment by eAndrius** [comment]
The issue was with the API library ( https://github.com/eAndrius/bitfinex-go ), fixed with: https://github.com/eAndrius/bitfinex-go/commit/637dcfdbfa56246b5b893b8a80f438ddc5d0f7e9

Thanks for reporting the error and please update.
