### ISSUE TITLE
Not lending

### ISSUE THREAD

**Issue by yhomega** [eAndrius/BitfinexLendingBot#6]
Hello
The bot is giving the following message but my btc/usd are not going into the lendbook, please help!

2015/09/07 17:20:19 Using Bitfinex user API key: IYx******************chRX7ITogJuuI1s

2015/09/07 17:20:19     Deposit wallet: 1*****\* btc (swappable: ***********\* btc)

2015/09/07 17:20:19     Cancelling all active btc offers...

2015/09/07 17:20:19     Getting current lendbook...

2015/09/07 17:20:20     Getting current wallet balance...

2015/09/07 17:20:20     Getting current btc ticker...

2015/09/07 17:20:20     Run done.

2015/09/07 17:20:20 Using Bitfinex user API key: **************************7ITogJuuI1s

2015/09/07 17:20:20     Deposit wallet: ***************_usd (swappable:**_******\* usd)

2015/09/07 17:20:20     Cancelling all active usd offers...

2015/09/07 17:20:20     Getting current lendbook...

2015/09/07 17:20:21     Getting current wallet balance...

2015/09/07 17:20:22     Run done.

2015/09/07 17:30:01 Using Bitfinex user API key: *******************************ITogJuuI1s

2015/09/07 17:30:01     Deposit wallet: ******************\* btc (swappable: *********8 btc)

2015/09/07 17:30:01     Cancelling all active btc offers...

2015/09/07 17:30:01     Getting current lendbook...

2015/09/07 17:30:02     Getting current wallet balance...

2015/09/07 17:30:02     Getting current btc ticker...

2015/09/07 17:30:02     Run done.

2015/09/07 17:30:02 Using Bitfinex user API key: **************************ogJuuI1s

2015/09/07 17:30:02     Deposit wallet: 2***************\* usd (swappable: **********\* usd)

2015/09/07 17:30:02     Cancelling all active usd offers...

2015/09/07 17:30:02     Getting current lendbook...

2015/09/07 17:30:03     Getting current wallet balance...

2015/09/07 17:30:03     Run done.

**Comment by whitj00** [comment]
@eAndrius

**Comment by eAndrius** [comment]
Unfortunately I can't reproduce the problem. Could you please share your config file? (don't forget to REMOVE API KEYS)
